include theos/makefiles/common.mk

TWEAK_NAME = screensavertweak
screensavertweak_FILES = Tweak.xm
screensavertweak_OBJ_FILES = /Users/tomcool/DVLP/ATV2/SMFramework/obj/SMFramework
screensavertweak_LDFLAGS=-undefined dynamic_lookup
screensavertweak_CFLAGS=-I../../ATV2Includes
include $(THEOS_MAKE_PATH)/tweak.mk
